spring.application.name=devtrails-backend

server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://localhost:3306/devtrails
spring.datasource.username=root
spring.datasource.password=0Successm@ntr@0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true